#include "xwork.h"

#include "src/xwork_core/xwork_core.c"
#include "src/xwork_workspace/xwork_workspace.c"
#include "src/xwork_tools/xwork_tools.c"
#include "src/xwork_orchestrator/xwork_orchestrator.c"
#include "src/xwork_policy/xwork_policy.c"
#include "src/xwork_persistence/xwork_persistence.c"
#include "src/xwork_artifacts/xwork_artifacts.c"
#include "src/xwork_host/xwork_host.c"
#include "src/xwork_profiles/xwork_profiles.c"
